kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/rancher/helm-unittest/

steps:
- name: build
  image: golang:1.16.5
  commands:
  - curl -L https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz | tar xvz 
  - mv linux-amd64/helm /usr/local/bin/helm && rm -rf linux-amd64
  - make rancher-build
  - make rancher-test
- name: build-all-binaries
  image: golang:1.16.5
  environment:
    CROSS: 1
    VERSION: ${DRONE_TAG}
  commands:
  - curl -L https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz | tar xvz 
  - mv linux-amd64/helm /usr/local/bin/helm && rm -rf linux-amd64
  - make build-rancher
  - make package-rancher
  when:
    instance:
    - drone-publish.rancher.io
    event: tag
- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - dist/artifacts/${DRONE_TAG}/helm-unittest_*
    api_key: 
      from_secret: github_token
  when:
    instance:
    - drone-publish.rancher.io
    event: tag
    ref:
      include: [ refs/tags/*rc* ]
- name: github_binary_release
  image: plugins/github-release
  settings:
    files:
    - dist/artifacts/${DRONE_TAG}/helm-unittest_*
    api_key: 
      from_secret: github_token
  when:
    instance:
    - drone-publish.rancher.io
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]