name: "unittest"
version: "0.2.0-rancher1"
usage: "unittest for helm charts"
description: "Unit test for helm chart in YAML with ease to keep your chart functional and robust."
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/untt"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./install-binary.sh"
  update: "cd $HELM_PLUGIN_DIR; HELM_PLUGIN_UPDATE=1 ./install-binary.sh"
